# Author: Ryan Sreenivasam
# Description: Serializers record the fields of each object in the database
# to provide an explanation of how to objects are converted into JSON

from rest_framework import serializers
from .models import Game

# This class will tell the REST framework how to serialize the Game model.
class GameSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Game
        fields = ('id', 'board', 'response', 'winner')
        # The id field is automatically generated by django and is required to 
        # access a specific game object in the database
