from rest_framework import serializers
from .models import Game


# This class will tell the REST framework how to serialize the Game model.
# The id field is automatically generated by django and is required to 
# access a specific game object.

class GameSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Game
        fields = ('id', 'board',)
