# Generated by Django 3.0.5 on 2020-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board',
            field=models.CharField(max_length=9),
        ),
    ]
