# Generated by Django 3.0.5 on 2020-04-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0004_game_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='active',
            new_name='response',
        ),
    ]
