# Generated by Django 3.0.5 on 2020-04-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0005_auto_20200420_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
